schema_version = "1.0.0"

id = "io_scene_bfres"

name = "BFRES Importer"
version = "2.0.0"
tagline = "Import BFRES files"
maintainer = "ranidspace"
type = "add-on"

tags = ["Import-Export"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

[permissions]
files = "Imports BFRES from disk"
